### ISSUE TITLE
Unhandled rejection Error: Invalid tag name "ember-frost-date=picker": Tags may not have any characters that encodeURIComponent encodes.

### ISSUE THREAD

**Issue by notmessenger** [ciena-frost/ember-frost-date-picker#79]
nvm version: 8.6.0

When running `ember install ember-frost-date-picker` receive this error:

```
Command failed: npm install --save-dev --loglevel error ember-frost-date=picker
Unhandled rejection Error: Invalid tag name "ember-frost-date=picker": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:76:15)
    at fromRegistry (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:265:13)
    at resolve (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:66:12)
    at npa (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:39:10)
    at /Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install/deps.js:200:16
    at /Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (<anonymous>)
    at /Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (<anonymous>)
    at asyncMap (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at exports.getAllMetadata (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install/deps.js:199:3)
    at Installer.loadArgMetadata (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install.js:325:3)
    at /Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install.js:656:16
    at BB.join.then (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install/read-shrinkwrap.js:41:16)
    at tryCatcher (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2017-11-06T14_05_45_940Z-debug.log

Error: Command failed: npm install --save-dev --loglevel error ember-frost-date=picker
Unhandled rejection Error: Invalid tag name "ember-frost-date=picker": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:76:15)
    at fromRegistry (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:265:13)
    at resolve (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:66:12)
    at npa (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:39:10)
    at /Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install/deps.js:200:16
    at /Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (<anonymous>)
    at /Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (<anonymous>)
    at asyncMap (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at exports.getAllMetadata (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install/deps.js:199:3)
    at Installer.loadArgMetadata (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install.js:325:3)
    at /Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install.js:656:16
    at BB.join.then (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/lib/install/read-shrinkwrap.js:41:16)
    at tryCatcher (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/me/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2017-11-06T14_05_45_940Z-debug.log

    at Promise.all.then.arr (/Users/me/Desktop/throwaway/buildSizeTest/node_modules/execa/index.js:210:11)
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by notmessenger** [comment]
Other addons in the Ciena family install just fine with this version of Node - there is just something about this repo specifically causing issues.

**Comment by srowhani** [comment]
I think you may have just typed it in wrong. I just tried and it seemed to work fine.

**Comment by notmessenger** [comment]
Likely so.  Have confirmed installs correctly
